


development: 
adapter: postgresql
 host: postgresql0.locum.ru
  database: olga312_rodnie73
  username: olga312_rodnie73
  password: 7ReOLesbm
  

 



production:
  adapter: postgresql
  host: postgresql0.locum.ru
  database: olga312_rodnie73
  username: olga312_rodnie73
  password: 7ReOLesbm

